version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/worklog_backend
    overwrite: yes
    file_exists_behavior: OVERWRITE

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
  ApplicationStart:
    - location: start.sh
      timeout: 60
