version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/worklog_backend
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /home/ubuntu/worklog_backend/scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: /home/ubuntu/worklog_backend/scripts/start.sh
      timeout: 60
