spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
