server:
  port: 8080
  servlet:
    context-path:
    encoding:
      charset: UTF-8

jwt:
  secret: ${JWT_SECRET}
  accessExpirationTime: ${JWT_EXPIRATION}
  refreshExpirationTime : ${JWT_REFRESH_EXPIRATION}

publishedAt: 0000-00-00

spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}