server:
  port: 8080
  servlet:
    context-path:
    encoding:
      charset: UTF-8

jwt:
  secret: ${JWT_SECRET}
  accessExpirationTime: ${JWT_EXPIRATION}

version: 1.0.3
spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}