spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}
      password: ${LOCAL_REDIS_PASSWORD}

logging:
  level:
    org:
      springframework: info

decorator:
  datasource:
    p6spy:
      enable-logging: true

springdoc:
  api-docs:
    enabled: true
